spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Cloud_Vendor?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug